[versions]
# Plugins
agp = "9.0.0"
bcv = "0.18.1"
maven-publish = "0.36.0"
screenshot = "0.0.1-alpha13"
spotless = "8.2.1"
detekt = "1.23.8"
mapsecrets = "2.0.1"

# Android
androidMinSdk = "26"
androidCompileSdk = "36"
androidTargetSdk = "36"

# Kotlin
kotlin = "2.2.21"

# Google
androidx-annotation = "1.9.1"

# Google - Compose
activityCompose = "1.12.4"
composeBom = "2025.11.00"
mapsCompose = "8.1.0"

# Other
kotlinx-coroutines = "1.10.2"
debugoverlay = "2.1.0"

# Testing
junit4 = "4.13.2"
truth = "1.4.5"
mockk = "1.14.9"
robolectric = "4.16.1"

[libraries]
# Google
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }

# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

# Other
debugoverlay = { module = "com.ms-square:debugoverlay", version.ref = "debugoverlay" }

# Testing
screenshot-validation-api = { group = "com.android.tools.screenshot", name = "screenshot-validation-api", version.ref = "screenshot" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
bcv = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bcv" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
mapsSecrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "mapsecrets" }
screenshot = { id = "com.android.compose.screenshot", version.ref = "screenshot" }
